language: node_js
node_js:
  - '4'
before_script:
  - 'cd $TRAVIS_BUILD_DIR'
  - 'echo "=============================="'
  - 'npm install -g http-server gulp'
  - 'npm install' # install npm packages
  - 'gulp'
  - 'npm install -g http-server'
  - 'http-server -p 8080 &'
  - 'cd $TRAVIS_BUILD_DIR/tests/bridge_stub'
  - 'node bridge.server.test &'
  - 'npm install phantom-jasmine -g'
script:
  - 'gulp test'
after_script:
after_success:
notifications:
  email:
  - bir.yuval@gmail.com